

import json

import xmlschema
import os



cpp_header_header = """
// This file is generated by pre_generator.py
#include "module.h"
#include "config.h"
#include <string>
#include <vector>
#include <map>
#include <optional>
"""

cpp_implementation_header = """
// This file is generated by pre_generator.py
#include "spine_types.h"

"""

class Spine_type:
    #@brief: Type_name: either "define", "using", "enum", "struct" or "class"
    type_name = ""
    depends_on = []
    name = ""
    code = ""
    to_json_code = ""
    from_json_code = ""
    upper_limit = None
    lower_limit = None
    #this is technically required but we dont check it
    regex_restriction = None

    def __init__(self, type_name, name, code):
        self.type_name = type_name
        self.name = name
        self.code = code
        self.depends_on = []

cpp_datatypes : list[Spine_type] = []


def remove_namespace(name):
    if name is not None:
        if "}" in name:
            return name.split("}", 1)[1]  # Entfernt den Namespace-URI
    else:
        return "None"
    return name

def to_cpp_datatype(type_name):
    type_name = str(type_name.__name__)
    type_mapping = {
        "string": "std::string",
        "str": "std::string",
        "int": "int",
        "float": "float",
        "double": "double",
        "boolean": "bool",
        "bool": "bool",
        "Duration": "uint64_t",
        "DateTime10": "uint64_t",
    }
    if type_name not in type_mapping:
        print("Unknown datatype:", type_name)
    return type_mapping.get(type_name, type_name)

def remove_duplicate_objects(spine_types: list[Spine_type]):
    seen = set()
    result = []
    for spine_type in spine_types:
        if spine_type.name not in seen:
            seen.add(spine_type.name)
            result.append(spine_type)
    return result

def sort_and_resolve_dependencies(spine_types: list[Spine_type]):
    type_order = {"define": 0, "using": 1, "enum": 2, "struct": 3, "class": 4}

    # Erstelle eine Abhängigkeits-Map
    dependency_map = {datatype.name: datatype.depends_on for datatype in cpp_datatypes}

    # Topologische Sortierung
    sorted_datatypes = []
    visited = set()

    def visit(datatype):
        if datatype.name in visited:
            return
        visited.add(datatype.name)
        for dependency in dependency_map.get(datatype.name, []):
            dependent_datatype = next((d for d in cpp_datatypes if d.name == dependency), None)
            if dependent_datatype:
                visit(dependent_datatype)
        sorted_datatypes.append(datatype)

    # Sortiere zuerst nach `type_order`, dann nach Abhängigkeiten
    cpp_datatypes.sort(key=lambda x: type_order.get(x.type_name, 5))
    for datatype in cpp_datatypes:
        visit(datatype)

    return sorted_datatypes

def make_variable_name(name: str):
    forbidden_names = ["switch", "auto", "SAR"]
    #Cleanup the variable so it can be used in C++
    name = ''.join(char if char.isalnum() else '_' for char in name)
    # Stelle sicher, dass der Name mit einem Buchstaben beginnt
    if not name[0].isalpha() or name[0] in forbidden_names:
        name = 'var_' + name
    return name

def process_complex_type(complex_type):
    global unprocessed_elements
    struct_type_name = remove_namespace(complex_type.name)
    new_type = Spine_type("struct", struct_type_name, "")
    if hasattr(complex_type.content, "content_type_label") and complex_type.content.content_type_label == "simple":
        print("simple type")
        unprocessed_elements += 1
    elif complex_type.content.model == "sequence":
        sequence_size = len(complex_type.content)
        new_type.code = f"struct {struct_type_name} {{\n"
        for elem in complex_type.content:
            variable_type = variable_name = ""
            if hasattr(elem, "model"):
                print(elem.model)
            else:
                variable_name = remove_namespace(elem.name)
                variable_type = remove_namespace(elem.type.name)
            new_type.code += f"\tstd::optional<{variable_type}> {variable_name} ;\n"
            # TODO: json parsers


        new_type.code += "};\n"
        cpp_datatypes.append(new_type)
        #print("type is sequence")
    #print("Generating code for complex type", remove_namespace(complex_type.name))
    # print("Generating code for complex type", remove_namespace(complex_type.name))



unprocessed_elements = 0
def process_schema(xml_schema):
    global unprocessed_elements
    #print("Generating code...")
    for simple_type in xml_schema.simple_types:

        if simple_type.derivation == "restriction":
            #restriction implies it is either a simple like "using Number = int" or an enum
            # Enum
            if simple_type.enumeration is not None:
                enum_type_name = remove_namespace(simple_type.name)
                new_type = Spine_type("enum",enum_type_name, "")
                #create enum and function headers
                new_type.code = "enum class " + enum_type_name + " {\n"
                new_type.to_json_code = f"""bool convertToJson(const {enum_type_name} &src, JsonVariant& dst) {{\n\tString enumName;\n\tswitch(src) {{\n"""
                new_type.from_json_code = f"""void convertFromJson(const JsonVariant& src, {enum_type_name} &dst) {{\n"""

                enum_variable_name = ""
                for enumeration in simple_type.enumeration:
                    enum_string_name = str(enumeration)
                    enum_variable_name = make_variable_name(enum_string_name)
                    new_type.code += "\t" + enum_variable_name + ",\n"
                    #switch case for enum->json
                    new_type.to_json_code += f"""\tcase {enum_type_name}::{enum_variable_name}:\n\t\t enumName = "{enum_string_name}";\n\t\tbreak;\n"""
                    #if return for json->enum
                    new_type.from_json_code += f"""\tif (src == "{enum_string_name}") {{\n\t\treturn {enum_type_name}::{enum_variable_name};\n\t}}\n"""

                #return empty string if enum->json fails (shouldn't happen)
                new_type.to_json_code += "\t} \n\t return enumName;\n}\n"
                #return last enum if json->enum fails
                new_type.from_json_code += f"""\t return {enum_type_name}::{enum_variable_name};\n}}\n"""
                new_type.code += "};\n"
                cpp_datatypes.append(new_type)
            # Using
            elif hasattr(simple_type, 'base_type'):
                new_type = Spine_type("using", remove_namespace(simple_type.name), "")
                new_type.code = "using " + remove_namespace(simple_type.name) + " = " + to_cpp_datatype(simple_type.base_type.python_type) + ";\n"
                found_restriction = False
                if simple_type.base_type.max_value is not None:
                    new_type.max_value = simple_type.base_type.max_value
                    pass
                if simple_type.base_type.min_value is not None:
                    found_restriction = True
                    new_type.min_value = simple_type.base_type.min_value
                    found_restriction = True
                if to_cpp_datatype(simple_type.base_type.python_type) == "std::string":
                    found_restriction = True
                if hasattr(simple_type.base_type.python_type, 'name'):
                    if simple_type.base_type.python_type.name == "duration":
                        found_restriction = True
                if not found_restriction:
                    print("Unknown restriction to basetype", simple_type.name)
                cpp_datatypes.append(new_type)
                pass
            else:
                unprocessed_elements += 1
                print("simple type: " + simple_type.name + " has restriction but no enumeration")
        else:
            # else its a struct
            # TODO: rework this so its more in line with the rest
            if hasattr(simple_type, 'member_types'):
                new_type = Spine_type("struct", remove_namespace(simple_type.name), "")
                new_type.code = "struct " + remove_namespace(simple_type.name) + " {\n"
                for member_type in simple_type.member_types:
                    if member_type.derivation == "restriction":
                        new_type.code += "\t" + remove_namespace(member_type.name) + " " + str(member_type.local_name).lower()  +";\n"
                    else:
                        new_type.code += "\t" + to_cpp_datatype(member_type.python_type) + " " + member_type.local_name  +";\n"
                new_type.code += "};\n"
                cpp_datatypes.append(new_type)
            else:
                print("No restriction to basetype", simple_type.name)
                unprocessed_elements += 1
    for complex_type in xml_schema.complex_types:
        process_complex_type(complex_type)

    for element in xml_schema.elements:
        pass
        #print("Generating code for element", remove_namespace(element))



print("Loading schema...")

schema_path = os.path.join("SPINE", "EEBus_SPINE_TS_NodeManagement.xsd")
# Schema laden
#schema = xmlschema.XMLSchema(schema_path)
#process_schema(schema)

spine_path = "SPINE"

for xsd in os.listdir(spine_path):
    if xsd.endswith(".xsd"):
        print("Processing: " + xsd)
        schema = xmlschema.XMLSchema(os.path.join(spine_path, xsd))
        process_schema(schema)


print("Deduplicating and sorting code...")
print("Before: ", len(cpp_datatypes))
cpp_datatypes = remove_duplicate_objects(cpp_datatypes)
cpp_datatypes = sort_and_resolve_dependencies(cpp_datatypes)
print("After: ", len(cpp_datatypes))
with open("spine_types.h", "w")as h, open("spine_types.cpp", "w") as cpp:
    h.write(cpp_header_header)
    cpp.write(cpp_implementation_header)
    #include "config.h"
    for datatype in cpp_datatypes:
        h.write(datatype.code)
        cpp.write(datatype.to_json_code)
        cpp.write(datatype.from_json_code)

print(f"Unprocessed elements: {unprocessed_elements}")

print("Done!")
